version: '3.5'
services:
  db:
    image: mysql:8.0.17
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./:/app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIME_ZONE}
    command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --skip-log-bin --default_authentication_plugin=mysql_native_password
